library(ape)
library(adegenet)
library(phangorn)
dna <- fasta2DNAbin("sequence-aligned-muscle.fasta")
print("data has been read")
D <- dist.dna(dna, model="TN93")
print("D")
tre <- nj(D)
tre <- ladderize(tre)
print("tre ladderize)")
plot(tre, cex=.6)
title("A simple NJ tree")
print("NJ Tree")
