library(ape)
library(adegenet)
library(phangorn)
dna <- fasta2DNAbin(file="sequence-aligned-muscle.fasta")
dna2 <- as.phyDat(dna)
tre.ini <- nj(dist.dna(dna,model="raw"))
parsimony(tre.ini, dna2)
tre.pars <- optim.parsimony(tre.ini, dna2)
plot(tre.pars, cex=0.6)
